name: Check Extension Build Status

on:
  workflow_dispatch:
  schedule:
    - cron: 0 19 */1 * *

jobs:
  calculate_errors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install --upgrade requests pandas numpy

    - name: Run Python script to calculate errors
      run: |
        python .github/get_build_status.py

